spring.mongodb.uri=mongodb+srv://AlamzebSiddique:Alamzeb%4078@cluster0.gwdoyie.mongodb.net/?appName=Cluster0
spring.mongodb.port=27017
spring.mongodb.database=journaldb
#spring.mongodb.auto-index-creation=true
spring.data.mongodb.auto-index-creation=true


